"""
User Variation Analysis
========================

Analyzes variation in serendipity scores across users to determine whether
mean serendipity is representative or if there's significant heterogeneity.

Answers the research question: "Is the average serendipity score meaningful
across all users, or should we segment users or report median instead?"

This addresses Pauline's feedback:
"Endelig score er gjennomsnitt av 100 brukere. Hvor mye variasjon ligger her?
Gir gjennomsnitt da en god tolkning eller nope for generelt?"

Prerequisites:
- recommendations.pkl (generated by PSOMOO.py or sensitivity_analysis_full.py)
- user_E_u.pkl (generated by PSOMOO.py or sensitivity_analysis_full.py)

Runtime: ~30 seconds

Output:
- user_variation_statistics.csv (summary table)
- user_variation_histograms.png (5-panel visualization)
- user_variation_report.txt (detailed analysis)
- Interpretation and recommendations

Author: [Your Name]
Date: 2026-04-24
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import os
from datetime import datetime
from scipy import stats

print("=" * 80)
print("USER VARIATION ANALYSIS")
print("=" * 80)
print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

# ============================================================================
# PART 1: LOAD PRE-COMPUTED RECOMMENDATIONS
# ============================================================================

print("[1/7] Loading pre-computed recommendations...")

# Check if pickle files exist
if not os.path.exists('recommendations.pkl'):
    print("❌ ERROR: recommendations.pkl not found!")
    print("   Please run PSOMOO.py or sensitivity_analysis_full.py first.")
    exit(1)

if not os.path.exists('user_E_u.pkl'):
    print("❌ ERROR: user_E_u.pkl not found!")
    print("   Please run PSOMOO.py or sensitivity_analysis_full.py first.")
    exit(1)

# Load data
recommendations = pickle.load(open('recommendations.pkl', 'rb'))
user_E_u = pickle.load(open('user_E_u.pkl', 'rb'))

print(f"  ✓ Loaded recommendations for {len(user_E_u)} users")
print(f"  ✓ Testing {len(recommendations)} different α values\n")

# Define alpha values and names
alphas = [0.0, 0.25, 0.5, 0.75, 1.0]
alpha_names = {
    0.0: 'Pure CF (α=0.0)',
    0.25: 'CF-Biased (α=0.25)',
    0.5: 'Balanced (α=0.5)',
    0.75: 'Distance-Biased (α=0.75)',
    1.0: 'Pure Distance (α=1.0)'
}

# ============================================================================
# PART 2: CALCULATE PER-USER SERENDIPITY
# ============================================================================

print("[2/7] Calculating per-user serendipity scores...")

# Serendipity thresholds (Ge et al., 2010)
DISTANCE_THRESHOLD = 0.7
CF_THRESHOLD = 1.8

def calculate_user_serendipity(user_recommendations, distance_threshold=0.7, cf_threshold=1.8):
    """
    Calculate serendipity score for a single user.
    
    Serendipity = proportion of recommendations that are BOTH:
    - Unexpected (distance > threshold)
    - Relevant (CF score > threshold)
    """
    if not user_recommendations:
        return 0.0
    
    serendipitous_count = 0
    
    for rec in user_recommendations:
        is_unexpected = rec['distance'] > distance_threshold
        is_relevant = rec['cf_score'] > cf_threshold
        
        if is_unexpected and is_relevant:
            serendipitous_count += 1
    
    return serendipitous_count / len(user_recommendations)


# Store per-user serendipity scores
user_serendipity_scores = {}

for alpha in alphas:
    user_serendipity_scores[alpha] = []
    
    for user_id in user_E_u.keys():
        user_recs = recommendations[alpha][user_id]
        user_score = calculate_user_serendipity(user_recs, DISTANCE_THRESHOLD, CF_THRESHOLD)
        user_serendipity_scores[alpha].append(user_score)
    
    print(f"  ✓ Calculated scores for {alpha_names[alpha]}")

print()

# ============================================================================
# PART 3: COMPUTE STATISTICS
# ============================================================================

print("[3/7] Computing statistical measures...")

statistics_data = []

for alpha in alphas:
    scores = np.array(user_serendipity_scores[alpha])
    
    # Basic statistics
    mean_score = np.mean(scores)
    std_score = np.std(scores)
    median_score = np.median(scores)
    min_score = np.min(scores)
    max_score = np.max(scores)
    
    # Quartiles
    q25 = np.percentile(scores, 25)
    q75 = np.percentile(scores, 75)
    iqr = q75 - q25
    
    # Coefficient of variation (relative variability)
    cv = (std_score / mean_score * 100) if mean_score > 0 else 0
    
    # Skewness and kurtosis
    skewness = stats.skew(scores)
    kurtosis = stats.kurtosis(scores)
    
    statistics_data.append({
        'Method': alpha_names[alpha],
        'Alpha': alpha,
        'Mean': mean_score,
        'Std': std_score,
        'Median': median_score,
        'Min': min_score,
        'Max': max_score,
        'Q25': q25,
        'Q75': q75,
        'IQR': iqr,
        'CV': cv,
        'Skewness': skewness,
        'Kurtosis': kurtosis,
        'N_Users': len(scores)
    })
    
    print(f"  ✓ {alpha_names[alpha]:30s}: mean={mean_score:.3f}, std={std_score:.3f}")

print()

# Create DataFrame
stats_df = pd.DataFrame(statistics_data)

# ============================================================================
# PART 4: INTERPRET VARIATION
# ============================================================================

print("[4/7] Interpreting variation levels...")

def interpret_variation(std, mean):
    """
    Interpret whether variation is low, moderate, or high.
    
    Rules of thumb:
    - std < 0.15: Low variation (mean is representative)
    - 0.15 ≤ std < 0.25: Moderate variation (mean acceptable, report std)
    - std ≥ 0.25: High variation (consider median or segmentation)
    """
    if std < 0.15:
        return "Low variation", "Report mean", "✓"
    elif std < 0.25:
        return "Moderate variation", "Report mean + std", "~"
    else:
        return "High variation", "Consider median/segmentation", "⚠"


# Add interpretation to DataFrame
interpretations = []
recommendations = []
indicators = []

for _, row in stats_df.iterrows():
    interp, rec, ind = interpret_variation(row['Std'], row['Mean'])
    interpretations.append(interp)
    recommendations.append(rec)
    indicators.append(ind)

stats_df['Interpretation'] = interpretations
stats_df['Recommendation'] = recommendations
stats_df['Indicator'] = indicators

# Print interpretation table
print("\n" + "=" * 80)
print("VARIATION ANALYSIS SUMMARY")
print("=" * 80)
print()

for _, row in stats_df.iterrows():
    print(f"{row['Method']}")
    print(f"  Mean:           {row['Mean']:.3f}")
    print(f"  Std:            {row['Std']:.3f}")
    print(f"  Median:         {row['Median']:.3f}")
    print(f"  Range:          [{row['Min']:.3f}, {row['Max']:.3f}]")
    print(f"  IQR:            {row['IQR']:.3f}")
    print(f"  CV:             {row['CV']:.1f}%")
    print(f"  Interpretation: {row['Interpretation']} {row['Indicator']}")
    print(f"  Recommendation: {row['Recommendation']}")
    print()

# ============================================================================
# PART 5: IDENTIFY BEST PERFORMING METHOD
# ============================================================================

print("=" * 80)
print("COMPARATIVE ANALYSIS")
print("=" * 80)
print()

# Find method with lowest std (most consistent)
most_consistent = stats_df.loc[stats_df['Std'].idxmin()]
print(f"Most Consistent Method: {most_consistent['Method']}")
print(f"  Std: {most_consistent['Std']:.3f} (lowest variation across users)")
print()

# Find method with highest mean
highest_mean = stats_df.loc[stats_df['Mean'].idxmax()]
print(f"Highest Mean Serendipity: {highest_mean['Method']}")
print(f"  Mean: {highest_mean['Mean']:.3f}")
print()

# Check if same method wins both
if most_consistent['Alpha'] == highest_mean['Alpha']:
    print(f"✓✓✓ {highest_mean['Method']} is BOTH:")
    print(f"    - Highest mean serendipity ({highest_mean['Mean']:.3f})")
    print(f"    - Most consistent across users (std={most_consistent['Std']:.3f})")
    print(f"\n→ Strong evidence for robustness!")
else:
    print(f"⚠ Trade-off exists:")
    print(f"  - Highest mean: {highest_mean['Method']}")
    print(f"  - Most consistent: {most_consistent['Method']}")

print()

# ============================================================================
# PART 6: CREATE VISUALIZATIONS
# ============================================================================

print("[5/7] Creating visualizations...")

# Set style
plt.style.use('ggplot')
sns.set_palette("husl")

# Create 5-panel histogram
fig, axes = plt.subplots(1, 5, figsize=(20, 4), sharey=True)

for i, alpha in enumerate(alphas):
    scores = user_serendipity_scores[alpha]
    mean_val = np.mean(scores)
    median_val = np.median(scores)
    std_val = np.std(scores)
    
    # Histogram
    axes[i].hist(scores, bins=20, edgecolor='black', alpha=0.7, color='skyblue')
    
    # Add mean line
    axes[i].axvline(mean_val, color='red', linestyle='--', linewidth=2, 
                    label=f'Mean: {mean_val:.2f}')
    
    # Add median line
    axes[i].axvline(median_val, color='green', linestyle='--', linewidth=2, 
                    label=f'Median: {median_val:.2f}')
    
    # Add std shading
    axes[i].axvspan(mean_val - std_val, mean_val + std_val, 
                    alpha=0.2, color='orange', label=f'±1 std: {std_val:.2f}')
    
    # Labels
    axes[i].set_title(alpha_names[alpha], fontweight='bold', fontsize=12)
    axes[i].set_xlabel('Serendipity Score', fontweight='bold')
    axes[i].legend(loc='upper left', fontsize=8)
    axes[i].set_xlim(0, 1)
    
    # Add interpretation text
    interp = stats_df[stats_df['Alpha'] == alpha]['Interpretation'].values[0]
    indicator = stats_df[stats_df['Alpha'] == alpha]['Indicator'].values[0]
    axes[i].text(0.95, 0.95, f'{interp}\n{indicator}', 
                transform=axes[i].transAxes,
                verticalalignment='top', horizontalalignment='right',
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5),
                fontsize=8)

# Overall y-label
axes[0].set_ylabel('Number of Users', fontweight='bold')

# Overall title
fig.suptitle('User Variation Analysis: Distribution of Serendipity Scores Across Users\n' +
             f'(N={len(user_E_u)} users, Ge et al. thresholds: distance>{DISTANCE_THRESHOLD}, CF>{CF_THRESHOLD})',
             fontsize=14, fontweight='bold', y=1.02)

plt.tight_layout()

# Save figure
hist_file = 'user_variation_histograms.png'
plt.savefig(hist_file, dpi=300, bbox_inches='tight')
print(f"  ✓ Saved: {hist_file}")

hist_pdf = 'user_variation_histograms.pdf'
plt.savefig(hist_pdf, bbox_inches='tight')
print(f"  ✓ Saved: {hist_pdf}")

plt.close()

# ============================================================================
# PART 6B: CREATE BOX PLOT COMPARISON
# ============================================================================

fig, ax = plt.subplots(figsize=(12, 6))

# Prepare data for box plot
box_data = [user_serendipity_scores[alpha] for alpha in alphas]
labels = [alpha_names[alpha] for alpha in alphas]

# Create box plot
bp = ax.boxplot(box_data, labels=labels, patch_artist=True, 
                showmeans=True, meanline=True)

# Color boxes
colors = ['lightgray', 'gold', 'skyblue', 'lightgreen', 'salmon']
for patch, color in zip(bp['boxes'], colors):
    patch.set_facecolor(color)
    patch.set_alpha(0.7)

# Styling
ax.set_ylabel('Serendipity Score', fontweight='bold', fontsize=12)
ax.set_xlabel('Weighting Strategy', fontweight='bold', fontsize=12)
ax.set_title('User Variation Comparison: Distribution of Serendipity Across Methods\n' +
             '(Box = IQR, Red line = Median, Green dashed = Mean)',
             fontweight='bold', fontsize=14)
ax.grid(True, alpha=0.3)
ax.set_ylim(0, 1.05)

# Rotate x-labels
plt.xticks(rotation=45, ha='right')

plt.tight_layout()

# Save
boxplot_file = 'user_variation_boxplot.png'
plt.savefig(boxplot_file, dpi=300, bbox_inches='tight')
print(f"  ✓ Saved: {boxplot_file}")

boxplot_pdf = 'user_variation_boxplot.pdf'
plt.savefig(boxplot_pdf, bbox_inches='tight')
print(f"  ✓ Saved: {boxplot_pdf}")

plt.close()

print()

# ============================================================================
# PART 7: SAVE RESULTS
# ============================================================================

print("[6/7] Saving results...")

# Save statistics CSV
csv_file = 'user_variation_statistics.csv'
stats_df.to_csv(csv_file, index=False, float_format='%.4f')
print(f"  ✓ Saved: {csv_file}")

# Save detailed report
report_file = 'user_variation_report.txt'
with open(report_file, 'w', encoding='utf-8') as f:
    f.write("=" * 80 + "\n")
    f.write("USER VARIATION ANALYSIS - DETAILED REPORT\n")
    f.write("=" * 80 + "\n")
    f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
    
    f.write("CONFIGURATION:\n")
    f.write(f"  Users analyzed: {len(user_E_u)}\n")
    f.write(f"  Recommendations per user: 10\n")
    f.write(f"  Distance threshold: > {DISTANCE_THRESHOLD}\n")
    f.write(f"  CF score threshold: > {CF_THRESHOLD}\n")
    f.write(f"  Alpha values tested: {len(alphas)}\n\n")
    
    f.write("=" * 80 + "\n")
    f.write("STATISTICAL SUMMARY\n")
    f.write("=" * 80 + "\n\n")
    
    for _, row in stats_df.iterrows():
        f.write(f"{row['Method']}\n")
        f.write(f"{'─' * 40}\n")
        f.write(f"  Mean:              {row['Mean']:.4f}\n")
        f.write(f"  Standard Deviation: {row['Std']:.4f}\n")
        f.write(f"  Median:            {row['Median']:.4f}\n")
        f.write(f"  Min:               {row['Min']:.4f}\n")
        f.write(f"  Max:               {row['Max']:.4f}\n")
        f.write(f"  Q25:               {row['Q25']:.4f}\n")
        f.write(f"  Q75:               {row['Q75']:.4f}\n")
        f.write(f"  IQR:               {row['IQR']:.4f}\n")
        f.write(f"  Coefficient of Variation: {row['CV']:.1f}%\n")
        f.write(f"  Skewness:          {row['Skewness']:.4f}\n")
        f.write(f"  Kurtosis:          {row['Kurtosis']:.4f}\n")
        f.write(f"\n  Interpretation:    {row['Interpretation']}\n")
        f.write(f"  Recommendation:    {row['Recommendation']}\n")
        f.write("\n")
    
    f.write("=" * 80 + "\n")
    f.write("KEY FINDINGS\n")
    f.write("=" * 80 + "\n\n")
    
    f.write(f"Most Consistent Method:\n")
    f.write(f"  {most_consistent['Method']}\n")
    f.write(f"  Standard Deviation: {most_consistent['Std']:.4f}\n\n")
    
    f.write(f"Highest Mean Serendipity:\n")
    f.write(f"  {highest_mean['Method']}\n")
    f.write(f"  Mean: {highest_mean['Mean']:.4f}\n\n")
    
    if most_consistent['Alpha'] == highest_mean['Alpha']:
        f.write(f"CONCLUSION:\n")
        f.write(f"  {highest_mean['Method']} achieves both highest mean AND lowest variation.\n")
        f.write(f"  This demonstrates robust performance across diverse user populations.\n")

print(f"  ✓ Saved: {report_file}")
print()

# ============================================================================
# FINAL SUMMARY
# ============================================================================

print("[7/7] Generating final summary...")
print()
print("=" * 80)
print("CONCLUSION AND RECOMMENDATIONS")
print("=" * 80)
print()

# Check if α=0.25 is best
alpha_025_stats = stats_df[stats_df['Alpha'] == 0.25].iloc[0]

print(f"For CF-Biased (α=0.25):")
print(f"  Mean serendipity:  {alpha_025_stats['Mean']:.3f}")
print(f"  Std deviation:     {alpha_025_stats['Std']:.3f}")
print(f"  Interpretation:    {alpha_025_stats['Interpretation']}")
print(f"  Recommendation:    {alpha_025_stats['Recommendation']}")
print()

if alpha_025_stats['Std'] < 0.15:
    print("✓✓✓ EXCELLENT NEWS!")
    print("    Low variation confirms that mean serendipity is representative.")
    print("    The α=0.25 finding is robust across diverse user populations.")
    print("    No need for user segmentation or median reporting.")
    print()
    print("FOR THESIS:")
    print(f'    "CF-Biased (α=0.25) achieved mean serendipity of {alpha_025_stats["Mean"]:.3f}')
    print(f'     with low variation across users (std={alpha_025_stats["Std"]:.3f}),')
    print('     demonstrating consistent performance across diverse listening profiles."')
elif alpha_025_stats['Std'] < 0.25:
    print("✓ GOOD NEWS!")
    print("   Moderate variation - mean is still acceptable.")
    print("   Recommend reporting both mean and standard deviation.")
    print()
    print("FOR THESIS:")
    print(f'   "CF-Biased (α=0.25) achieved mean serendipity of {alpha_025_stats["Mean"]:.3f}')
    print(f'    (std={alpha_025_stats["Std"]:.3f}), indicating moderate consistency')
    print('    across users."')
else:
    print("⚠ HIGH VARIATION DETECTED")
    print("  Consider reporting median or segmenting users.")
    print("  High heterogeneity suggests different user types benefit differently.")
    print()
    print("FOR THESIS:")
    print(f'  "CF-Biased (α=0.25) achieved median serendipity of {alpha_025_stats["Median"]:.3f}')
    print(f'   with significant variation across users (std={alpha_025_stats["Std"]:.3f}),')
    print('   suggesting potential for personalized α selection."')

print()
print("=" * 80)
print(f"Completed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print("=" * 80)
print()
print("Generated files:")
print("  1. user_variation_statistics.csv")
print("  2. user_variation_histograms.png/pdf (5-panel distribution)")
print("  3. user_variation_boxplot.png/pdf (comparison across methods)")
print("  4. user_variation_report.txt (detailed analysis)")
print()
print("Next step: Review visualizations and include in thesis discussion!")
print()